# Generated by Django 4.2 on 2025-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_shortlisted',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
