# Generated by Django 4.2 on 2025-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_candidate_cv_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
